name: CI react!

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: build react app
        run: |
          echo "installing dependencies"
          npm install
          echo "building project"
          npm run build




